### ISSUE TITLE
Is this project still working? :)

### ISSUE THREAD

**Issue by mxaddict** [p4u/stratum-proxy-ng#3]
Is this project still working? :) And if not, could you point me in the direction that is broken or needs working on and I will contribute cause I need a stratum -> stratum proxy that will work for multiple algos.

Thanks

**Comment by p4u** [comment]
I don't have plans for maintaining it in the short term cause a lack of time and resources (funding).

The code is still working as far as I know. But I've not tested it since some years ago. Most of the things where implemented and working. Maybe things has changed a bit now, so the best you can do is to test it.
